### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by 2803media** [Anorov/PySocks#102]
Hi when I use the proxy (with python3) like that 

```
import socks
import socket

proxy_host = 'proxy-nl.privateinternetaccess.com'
proxy_port = '1080'
proxy_username = 'user'
proxy_password = 'pass'


socks.set_default_proxy(socks.PROXY_TYPE_SOCKS5,proxy_host,proxy_port,True,proxy_username,proxy_password)
socket.socket = socks.socksocket

import urllib3

http = urllib3.PoolManager()
r = http.request('GET', 'http://www.domaine.fr')
print(r.status)

```

And I've got this error:

```
Traceback (most recent call last):
  File "/home/data-prospection/public_html/test/check.py", line 19, in <module>
    r = http.request('GET', 'http://www.domaine.fr')
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 153, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 154, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 133, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
  File "/usr/local/lib/python3.4/dist-packages/socks.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/socks.py", line 832, in connect
    super(socksocket, self).connect(proxy_addr)
TypeError: an integer is required (got type str)
```

Thanks for your kind help i'm stuck here ;)

**Comment by 2803media** [comment]
Damned I just found the problem....

proxy_port = 1080

Instead of 
proxy_port = '1080'
