### ISSUE TITLE
Socks5 proxy and gevent error AttributeError: 'super' object has no attribute 'getpeername

### ISSUE THREAD

**Issue by masolit** [Anorov/PySocks#65]
# same problem after update

# urllib
```python
from gevent import monkey
monkey.patch_all()

import urllib.request
import socks
from sockshandler import SocksiPyHandler

request = urllib.request.Request('http://myip.dnsomatic.com')
opener = urllib.request.build_opener(SocksiPyHandler(socks.SOCKS5, '127.0.0.1', 9050))
urllib.request.install_opener(opener)

handle = urllib.request.urlopen(request, timeout=60)
print(handle.read())
```
```
Traceback (most recent call last):
  File "/home/masolit/IdeaProjects/Python/scraping/tor_reqests2.py", line 28, in <module>
    handle = urllib.request.urlopen(request, timeout=60)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/sockshandler.py", line 62, in http_open
    return self.do_open(build, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/sockshandler.py", line 35, in connect
    self.sock.settimeout(self.timeout)
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/socks.py", line 288, in settimeout
    peer = self.get_proxy_peername()
  File "/home/masolit/.virtualenvs/sandbox/lib/python3.6/site-packages/socks.py", line 429, in get_proxy_peername
    return super(socksocket, self).getpeername()
AttributeError: 'super' object has no attribute 'getpeername'
```

**Comment by Anorov** [comment]
Including if you do a `git pull`? (I'll push the change to PyPI today.)

**Comment by Anorov** [comment]
I believe this should be resolved now, thanks.
