### ISSUE TITLE
IPV6 not supported

### ISSUE THREAD

**Issue by FloFromAT** [Anorov/PySocks#83]
s = socks.socksocket()
s.set_proxy(socks.SOCKS4, "10.10.10.10", 1080)
>>> s.connect('www.google.com')                                                                          
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/socks.py", line 96, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/socks.py", line 752, in connect
    raise socket.error("PySocks doesn't support IPv6: %s" % str(dest_pair))
OSError: PySocks doesn't support IPv6: www.google.com

**Comment by quybvs** [comment]
s.connect(('www.google.com',80))

**Comment by Anorov** [comment]
Please see @quybvs's answer. Thanks.
